export const SEE_ALL = "See All"
export const WRITE_AMOUNT = "Write Amount"
export const SEND = "Send"
export const ABOUT_A_CARD = "Credit Card generally means a plastic card issued by Scheduled Commercial Banks assigned to a Cardholder, with a credit limit, that can be used to purchase goods and services on credit or obtain cash advances."

export const ACTIVE_LOANS = "Active Loans Overview"
export const SIGN_IN = "Sign in"
export const SIGN_UP = "Sign up"
export const ALREADY_HAVE_ACC = "Already have an account?"
export const CREATE_NEW_ACC = "Create New Account?" 